import { DEFAULT_INTERCOM_REQUEST_TIMEOUT_MS } from 'lib/intercom';

import {
  CONFIRMATION_REQUEST_TIMEOUT_GRACE_MS,
  DAPP_CONFIRMATION_AUTODECLINE_MS,
  IN_WALLET_CONFIRMATION_AUTODECLINE_MS,
  LEDGER_CONFIRMATION_REQUEST_TIMEOUT_MS
} from './confirmation-timeouts';
import { TempleMessageType } from './types';

export const IN_WALLET_CONFIRMATION_REQUEST_TIMEOUT_MS =
  IN_WALLET_CONFIRMATION_AUTODECLINE_MS + CONFIRMATION_REQUEST_TIMEOUT_GRACE_MS;
export const DAPP_CONFIRMATION_REQUEST_TIMEOUT_MS =
  DAPP_CONFIRMATION_AUTODECLINE_MS + CONFIRMATION_REQUEST_TIMEOUT_GRACE_MS;

const REQUEST_TIMEOUTS: Partial<Record<TempleMessageType, number>> = {
  [TempleMessageType.OperationsRequest]: IN_WALLET_CONFIRMATION_REQUEST_TIMEOUT_MS,
  [TempleMessageType.SignRequest]: IN_WALLET_CONFIRMATION_REQUEST_TIMEOUT_MS,
  [TempleMessageType.PageRequest]: DAPP_CONFIRMATION_REQUEST_TIMEOUT_MS,
  [TempleMessageType.DAppPermConfirmationRequest]: DAPP_CONFIRMATION_REQUEST_TIMEOUT_MS,
  [TempleMessageType.DAppOpsConfirmationRequest]: DAPP_CONFIRMATION_REQUEST_TIMEOUT_MS,
  [TempleMessageType.DAppSignConfirmationRequest]: DAPP_CONFIRMATION_REQUEST_TIMEOUT_MS,
  [TempleMessageType.CreateLedgerAccountRequest]: LEDGER_CONFIRMATION_REQUEST_TIMEOUT_MS,
  [TempleMessageType.GetLedgerTezosPkRequest]: LEDGER_CONFIRMATION_REQUEST_TIMEOUT_MS
};

export const getTempleRequestTimeoutMs = (type: TempleMessageType) =>
  REQUEST_TIMEOUTS[type] ?? DEFAULT_INTERCOM_REQUEST_TIMEOUT_MS;
