name: Code quality

on:
  pull_request:
    branches:
      - develop

env:
  TEMPLE_WALLET_LEDGER_BRIDGE_URL: ${{ secrets.TEMPLE_WALLET_LEDGER_BRIDGE_URL }}
  TEMPLE_WALLET_LOGO_URL: ${{ secrets.TEMPLE_WALLET_LOGO_URL }}
  TEMPLE_WALLET_LV_ACCOUNT_PKH: ${{ secrets.TEMPLE_WALLET_LV_ACCOUNT_PKH }}
  TEMPLE_WALLET_LV_ACCOUNT_PUBLIC_KEY: ${{ secrets.TEMPLE_WALLET_LV_ACCOUNT_PUBLIC_KEY }}

jobs:
  code-quality:
    name: Checks if ts, lint, unit tests & build work
    runs-on: ubuntu-latest
    environment: develop-environment
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: yarn install

      - run: yarn ci

      - run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/chrome.zip
          if-no-files-found: error
          retention-days: 7
